<?php declare(strict_types=1);

use GuardsmanPanda\Larabear\Infrastructure\Database\Service\BearDatabaseService;
use Illuminate\Database\Migrations\Migration;
use Illuminate\Database\Schema\Blueprint;
use Illuminate\Support\Facades\DB;
use Illuminate\Support\Facades\Schema;

return new class extends Migration {
    public function up(): void {
        Schema::create(table: 'bear_country', callback: static function (Blueprint $table) {
            if (BearDatabaseService::defaultConnectionDriver() === 'pgsql') {
                $table->text(column: 'cca2')->primary();
                $table->text(column: 'cca3')->unique();
            } else {
                $table->string(column: 'cca2')->primary();
                $table->string(column: 'cca3')->unique();
            }
            $table->text(column: 'name');
            $table->text(column: 'tld');
            $table->text(column: 'calling_code');
            $table->text(column: 'currency_code');
            $table->text(column: 'dependency_status')->nullable();
            $table->timestampTz(column: 'created_at')->default(DB::raw(value: 'CURRENT_TIMESTAMP'));
            $table->timestampTz(column: 'updated_at')->default(DB::raw(value: 'CURRENT_TIMESTAMP'));
        });

        $country = array(
            array("cca2" => "FR", "cca3" => "FRA", "name" => "France", "tld" => ".fr", "calling_code" => "33", "currency_code" => "EUR", "dependency_status" => null),
            array("cca2" => "IN", "cca3" => "IND", "name" => "India", "tld" => ".in", "calling_code" => "91", "currency_code" => "INR", "dependency_status" => null),
            array("cca2" => "PK", "cca3" => "PAK", "name" => "Pakistan", "tld" => ".pk", "calling_code" => "92", "currency_code" => "PKR", "dependency_status" => null),
            array("cca2" => "US", "cca3" => "USA", "name" => "United States", "tld" => ".us", "calling_code" => "1", "currency_code" => "USD", "dependency_status" => null),
            array("cca2" => "NG", "cca3" => "NGA", "name" => "Nigeria", "tld" => ".ng", "calling_code" => "234", "currency_code" => "NGN", "dependency_status" => null),
            array("cca2" => "GB-ENG", "cca3" => "GB-ENG", "name" => "England", "tld" => ".uk", "calling_code" => "44", "currency_code" => "GBP", "dependency_status" => "Part of the UK"),
            array("cca2" => "GB-SCT", "cca3" => "GB-SCT", "name" => "Scotland", "tld" => ".scot", "calling_code" => "44", "currency_code" => "GBP", "dependency_status" => "Part of the UK"),
            array("cca2" => "GB-NIR", "cca3" => "GB-NIR", "name" => "Northern Ireland", "tld" => ".uk", "calling_code" => "44", "currency_code" => "GBP", "dependency_status" => "Part of the UK"),
            array("cca2" => "WS", "cca3" => "WSM", "name" => "Samoa", "tld" => ".ws", "calling_code" => "685", "currency_code" => "WST", "dependency_status" => null),
            array("cca2" => "CN", "cca3" => "CHN", "name" => "China", "tld" => ".cn", "calling_code" => "86", "currency_code" => "CNY", "dependency_status" => null),
            array("cca2" => "ID", "cca3" => "IDN", "name" => "Indonesia", "tld" => ".id", "calling_code" => "62", "currency_code" => "IDR", "dependency_status" => null),
            array("cca2" => "BR", "cca3" => "BRA", "name" => "Brazil", "tld" => ".br", "calling_code" => "55", "currency_code" => "BRL", "dependency_status" => null),
            array("cca2" => "BD", "cca3" => "BGD", "name" => "Bangladesh", "tld" => ".bd", "calling_code" => "880", "currency_code" => "BDT", "dependency_status" => null),
            array("cca2" => "RU", "cca3" => "RUS", "name" => "Russia", "tld" => ".ru", "calling_code" => "7", "currency_code" => "RUB", "dependency_status" => null),
            array("cca2" => "JP", "cca3" => "JPN", "name" => "Japan", "tld" => ".jp", "calling_code" => "81", "currency_code" => "JPY", "dependency_status" => null),
            array("cca2" => "MX", "cca3" => "MEX", "name" => "Mexico", "tld" => ".mx", "calling_code" => "52", "currency_code" => "MXN", "dependency_status" => null),
            array("cca2" => "PH", "cca3" => "PHL", "name" => "Philippines", "tld" => ".ph", "calling_code" => "63", "currency_code" => "PHP", "dependency_status" => null),
            array("cca2" => "VN", "cca3" => "VNM", "name" => "Vietnam", "tld" => ".vn", "calling_code" => "84", "currency_code" => "VND", "dependency_status" => null),
            array("cca2" => "ET", "cca3" => "ETH", "name" => "Ethiopia", "tld" => ".et", "calling_code" => "251", "currency_code" => "ETB", "dependency_status" => null),
            array("cca2" => "EG", "cca3" => "EGY", "name" => "Egypt", "tld" => ".eg", "calling_code" => "20", "currency_code" => "EGP", "dependency_status" => null),
            array("cca2" => "CD", "cca3" => "COD", "name" => "Congo - Kinshasa", "tld" => ".cd", "calling_code" => "243", "currency_code" => "CDF", "dependency_status" => null),
            array("cca2" => "DE", "cca3" => "DEU", "name" => "Germany", "tld" => ".de", "calling_code" => "49", "currency_code" => "EUR", "dependency_status" => null),
            array("cca2" => "IR", "cca3" => "IRN", "name" => "Iran", "tld" => ".ir", "calling_code" => "98", "currency_code" => "IRR", "dependency_status" => null),
            array("cca2" => "TR", "cca3" => "TUR", "name" => "Turkey", "tld" => ".tr", "calling_code" => "90", "currency_code" => "TRY", "dependency_status" => null),
            array("cca2" => "TH", "cca3" => "THA", "name" => "Thailand", "tld" => ".th", "calling_code" => "66", "currency_code" => "THB", "dependency_status" => null),
            array("cca2" => "GB", "cca3" => "GBR", "name" => "United Kingdom", "tld" => ".uk", "calling_code" => "44", "currency_code" => "GBP", "dependency_status" => null),
            array("cca2" => "IT", "cca3" => "ITA", "name" => "Italy", "tld" => ".it", "calling_code" => "39", "currency_code" => "EUR", "dependency_status" => null),
            array("cca2" => "ZA", "cca3" => "ZAF", "name" => "South Africa", "tld" => ".za", "calling_code" => "27", "currency_code" => "ZAR", "dependency_status" => null),
            array("cca2" => "TZ", "cca3" => "TZA", "name" => "Tanzania", "tld" => ".tz", "calling_code" => "255", "currency_code" => "TZS", "dependency_status" => null),
            array("cca2" => "MM", "cca3" => "MMR", "name" => "Myanmar", "tld" => ".mm", "calling_code" => "95", "currency_code" => "MMK", "dependency_status" => null),
            array("cca2" => "KR", "cca3" => "KOR", "name" => "South Korea", "tld" => ".kr", "calling_code" => "82", "currency_code" => "KRW", "dependency_status" => null),
            array("cca2" => "CO", "cca3" => "COL", "name" => "Colombia", "tld" => ".co", "calling_code" => "57", "currency_code" => "COP", "dependency_status" => null),
            array("cca2" => "KE", "cca3" => "KEN", "name" => "Kenya", "tld" => ".ke", "calling_code" => "254", "currency_code" => "KES", "dependency_status" => null),
            array("cca2" => "ES", "cca3" => "ESP", "name" => "Spain", "tld" => ".es", "calling_code" => "34", "currency_code" => "EUR", "dependency_status" => null),
            array("cca2" => "AR", "cca3" => "ARG", "name" => "Argentina", "tld" => ".ar", "calling_code" => "54", "currency_code" => "ARS", "dependency_status" => null),
            array("cca2" => "DZ", "cca3" => "DZA", "name" => "Algeria", "tld" => ".dz", "calling_code" => "213", "currency_code" => "DZD", "dependency_status" => null),
            array("cca2" => "UA", "cca3" => "UKR", "name" => "Ukraine", "tld" => ".ua", "calling_code" => "380", "currency_code" => "UAH", "dependency_status" => null),
            array("cca2" => "SD", "cca3" => "SDN", "name" => "Sudan", "tld" => ".sd", "calling_code" => "249", "currency_code" => "SDG", "dependency_status" => null),
            array("cca2" => "PL", "cca3" => "POL", "name" => "Poland", "tld" => ".pl", "calling_code" => "48", "currency_code" => "PLN", "dependency_status" => null),
            array("cca2" => "IQ", "cca3" => "IRQ", "name" => "Iraq", "tld" => ".iq", "calling_code" => "964", "currency_code" => "IQD", "dependency_status" => null),
            array("cca2" => "AF", "cca3" => "AFG", "name" => "Afghanistan", "tld" => ".af", "calling_code" => "93", "currency_code" => "AFN", "dependency_status" => null),
            array("cca2" => "CA", "cca3" => "CAN", "name" => "Canada", "tld" => ".ca", "calling_code" => "1", "currency_code" => "CAD", "dependency_status" => null),
            array("cca2" => "UG", "cca3" => "UGA", "name" => "Uganda", "tld" => ".ug", "calling_code" => "256", "currency_code" => "UGX", "dependency_status" => null),
            array("cca2" => "MA", "cca3" => "MAR", "name" => "Morocco", "tld" => ".ma", "calling_code" => "212", "currency_code" => "MAD", "dependency_status" => null),
            array("cca2" => "SA", "cca3" => "SAU", "name" => "Saudi Arabia", "tld" => ".sa", "calling_code" => "966", "currency_code" => "SAR", "dependency_status" => null),
            array("cca2" => "UZ", "cca3" => "UZB", "name" => "Uzbekistan", "tld" => ".uz", "calling_code" => "998", "currency_code" => "UZS", "dependency_status" => null),
            array("cca2" => "PE", "cca3" => "PER", "name" => "Peru", "tld" => ".pe", "calling_code" => "51", "currency_code" => "PEN", "dependency_status" => null),
            array("cca2" => "MY", "cca3" => "MYS", "name" => "Malaysia", "tld" => ".my", "calling_code" => "60", "currency_code" => "MYR", "dependency_status" => null),
            array("cca2" => "VE", "cca3" => "VEN", "name" => "Venezuela", "tld" => ".ve", "calling_code" => "58", "currency_code" => "VES", "dependency_status" => null),
            array("cca2" => "NP", "cca3" => "NPL", "name" => "Nepal", "tld" => ".np", "calling_code" => "977", "currency_code" => "NPR", "dependency_status" => null),
            array("cca2" => "GH", "cca3" => "GHA", "name" => "Ghana", "tld" => ".gh", "calling_code" => "233", "currency_code" => "GHS", "dependency_status" => null),
            array("cca2" => "YE", "cca3" => "YEM", "name" => "Yemen", "tld" => ".ye", "calling_code" => "967", "currency_code" => "YER", "dependency_status" => null),
            array("cca2" => "MZ", "cca3" => "MOZ", "name" => "Mozambique", "tld" => ".mz", "calling_code" => "258", "currency_code" => "MZN", "dependency_status" => null),
            array("cca2" => "AO", "cca3" => "AGO", "name" => "Angola", "tld" => ".ao", "calling_code" => "244", "currency_code" => "AOA", "dependency_status" => null),
            array("cca2" => "KP", "cca3" => "PRK", "name" => "North Korea", "tld" => ".kp", "calling_code" => "850", "currency_code" => "KPW", "dependency_status" => null),
            array("cca2" => "AU", "cca3" => "AUS", "name" => "Australia", "tld" => ".au", "calling_code" => "61", "currency_code" => "AUD", "dependency_status" => null),
            array("cca2" => "TW", "cca3" => "TWN", "name" => "Taiwan", "tld" => ".tw", "calling_code" => "886", "currency_code" => "TWD", "dependency_status" => null),
            array("cca2" => "CM", "cca3" => "CMR", "name" => "Cameroon", "tld" => ".cm", "calling_code" => "237", "currency_code" => "XAF", "dependency_status" => null),
            array("cca2" => "CI", "cca3" => "CIV", "name" => "Côte d’Ivoire", "tld" => ".ci", "calling_code" => "225", "currency_code" => "XOF", "dependency_status" => null),
            array("cca2" => "MG", "cca3" => "MDG", "name" => "Madagascar", "tld" => ".mg", "calling_code" => "261", "currency_code" => "MGA", "dependency_status" => null),
            array("cca2" => "LK", "cca3" => "LKA", "name" => "Sri Lanka", "tld" => ".lk", "calling_code" => "94", "currency_code" => "LKR", "dependency_status" => null),
            array("cca2" => "NE", "cca3" => "NER", "name" => "Niger", "tld" => ".ne", "calling_code" => "227", "currency_code" => "XOF", "dependency_status" => null),
            array("cca2" => "RO", "cca3" => "ROU", "name" => "Romania", "tld" => ".ro", "calling_code" => "40", "currency_code" => "RON", "dependency_status" => null),
            array("cca2" => "BF", "cca3" => "BFA", "name" => "Burkina Faso", "tld" => ".bf", "calling_code" => "226", "currency_code" => "XOF", "dependency_status" => null),
            array("cca2" => "SY", "cca3" => "SYR", "name" => "Syria", "tld" => ".sy", "calling_code" => "963", "currency_code" => "SYP", "dependency_status" => null),
            array("cca2" => "CL", "cca3" => "CHL", "name" => "Chile", "tld" => ".cl", "calling_code" => "56", "currency_code" => "CLP", "dependency_status" => null),
            array("cca2" => "ML", "cca3" => "MLI", "name" => "Mali", "tld" => ".ml", "calling_code" => "223", "currency_code" => "XOF", "dependency_status" => null),
            array("cca2" => "KZ", "cca3" => "KAZ", "name" => "Kazakhstan", "tld" => ".kz", "calling_code" => "7", "currency_code" => "KZT", "dependency_status" => null),
            array("cca2" => "NL", "cca3" => "NLD", "name" => "Netherlands", "tld" => ".nl", "calling_code" => "31", "currency_code" => "EUR", "dependency_status" => null),
            array("cca2" => "MW", "cca3" => "MWI", "name" => "Malawi", "tld" => ".mw", "calling_code" => "265", "currency_code" => "MWK", "dependency_status" => null),
            array("cca2" => "EC", "cca3" => "ECU", "name" => "Ecuador", "tld" => ".ec", "calling_code" => "593", "currency_code" => "USD", "dependency_status" => null),
            array("cca2" => "GT", "cca3" => "GTM", "name" => "Guatemala", "tld" => ".gt", "calling_code" => "502", "currency_code" => "GTQ", "dependency_status" => null),
            array("cca2" => "ZM", "cca3" => "ZMB", "name" => "Zambia", "tld" => ".zm", "calling_code" => "260", "currency_code" => "ZMW", "dependency_status" => null),
            array("cca2" => "KH", "cca3" => "KHM", "name" => "Cambodia", "tld" => ".kh", "calling_code" => "855", "currency_code" => "KHR", "dependency_status" => null),
            array("cca2" => "SN", "cca3" => "SEN", "name" => "Senegal", "tld" => ".sn", "calling_code" => "221", "currency_code" => "XOF", "dependency_status" => null),
            array("cca2" => "TD", "cca3" => "TCD", "name" => "Chad", "tld" => ".td", "calling_code" => "235", "currency_code" => "XAF", "dependency_status" => null),
            array("cca2" => "ZW", "cca3" => "ZWE", "name" => "Zimbabwe", "tld" => ".zw", "calling_code" => "263", "currency_code" => "ZWL", "dependency_status" => null),
            array("cca2" => "GN", "cca3" => "GIN", "name" => "Guinea", "tld" => ".gn", "calling_code" => "224", "currency_code" => "GNF", "dependency_status" => null),
            array("cca2" => "SS", "cca3" => "SSD", "name" => "South Sudan", "tld" => ".ss", "calling_code" => "211", "currency_code" => "SSP", "dependency_status" => null),
            array("cca2" => "RW", "cca3" => "RWA", "name" => "Rwanda", "tld" => ".rw", "calling_code" => "250", "currency_code" => "RWF", "dependency_status" => null),
            array("cca2" => "BE", "cca3" => "BEL", "name" => "Belgium", "tld" => ".be", "calling_code" => "32", "currency_code" => "EUR", "dependency_status" => null),
            array("cca2" => "CU", "cca3" => "CUB", "name" => "Cuba", "tld" => ".cu", "calling_code" => "53", "currency_code" => "CUP,CUC", "dependency_status" => null),
            array("cca2" => "TN", "cca3" => "TUN", "name" => "Tunisia", "tld" => ".tn", "calling_code" => "216", "currency_code" => "TND", "dependency_status" => null),
            array("cca2" => "SO", "cca3" => "SOM", "name" => "Somalia", "tld" => ".so", "calling_code" => "252", "currency_code" => "SOS", "dependency_status" => null),
            array("cca2" => "HT", "cca3" => "HTI", "name" => "Haiti", "tld" => ".ht", "calling_code" => "509", "currency_code" => "HTG,USD", "dependency_status" => null),
            array("cca2" => "BO", "cca3" => "BOL", "name" => "Bolivia", "tld" => ".bo", "calling_code" => "591", "currency_code" => "BOB", "dependency_status" => null),
            array("cca2" => "GR", "cca3" => "GRC", "name" => "Greece", "tld" => ".gr", "calling_code" => "30", "currency_code" => "EUR", "dependency_status" => null),
            array("cca2" => "BJ", "cca3" => "BEN", "name" => "Benin", "tld" => ".bj", "calling_code" => "229", "currency_code" => "XOF", "dependency_status" => null),
            array("cca2" => "CZ", "cca3" => "CZE", "name" => "Czechia", "tld" => ".cz", "calling_code" => "420", "currency_code" => "CZK", "dependency_status" => null),
            array("cca2" => "PT", "cca3" => "PRT", "name" => "Portugal", "tld" => ".pt", "calling_code" => "351", "currency_code" => "EUR", "dependency_status" => null),
            array("cca2" => "BI", "cca3" => "BDI", "name" => "Burundi", "tld" => ".bi", "calling_code" => "257", "currency_code" => "BIF", "dependency_status" => null),
            array("cca2" => "DO", "cca3" => "DOM", "name" => "Dominican Republic", "tld" => ".do", "calling_code" => "1-809,1-829,1-849", "currency_code" => "DOP", "dependency_status" => null),
            array("cca2" => "SE", "cca3" => "SWE", "name" => "Sweden", "tld" => ".se", "calling_code" => "46", "currency_code" => "SEK", "dependency_status" => null),
            array("cca2" => "AE", "cca3" => "ARE", "name" => "United Arab Emirates", "tld" => ".ae", "calling_code" => "971", "currency_code" => "AED", "dependency_status" => null),
            array("cca2" => "HU", "cca3" => "HUN", "name" => "Hungary", "tld" => ".hu", "calling_code" => "36", "currency_code" => "HUF", "dependency_status" => null),
            array("cca2" => "AZ", "cca3" => "AZE", "name" => "Azerbaijan", "tld" => ".az", "calling_code" => "994", "currency_code" => "AZN", "dependency_status" => null),
            array("cca2" => "JO", "cca3" => "JOR", "name" => "Jordan", "tld" => ".jo", "calling_code" => "962", "currency_code" => "JOD", "dependency_status" => null),
            array("cca2" => "BY", "cca3" => "BLR", "name" => "Belarus", "tld" => ".by", "calling_code" => "375", "currency_code" => "BYN", "dependency_status" => null),
            array("cca2" => "AT", "cca3" => "AUT", "name" => "Austria", "tld" => ".at", "calling_code" => "43", "currency_code" => "EUR", "dependency_status" => null),
            array("cca2" => "TJ", "cca3" => "TJK", "name" => "Tajikistan", "tld" => ".tj", "calling_code" => "992", "currency_code" => "TJS", "dependency_status" => null),
            array("cca2" => "HN", "cca3" => "HND", "name" => "Honduras", "tld" => ".hn", "calling_code" => "504", "currency_code" => "HNL", "dependency_status" => null),
            array("cca2" => "IL", "cca3" => "ISR", "name" => "Israel", "tld" => ".il", "calling_code" => "972", "currency_code" => "ILS", "dependency_status" => null),
            array("cca2" => "CH", "cca3" => "CHE", "name" => "Switzerland", "tld" => ".ch", "calling_code" => "41", "currency_code" => "CHF", "dependency_status" => null),
            array("cca2" => "PG", "cca3" => "PNG", "name" => "Papua New Guinea", "tld" => ".pg", "calling_code" => "675", "currency_code" => "PGK", "dependency_status" => null),
            array("cca2" => "HK", "cca3" => "HKG", "name" => "Hong Kong", "tld" => ".hk", "calling_code" => "852", "currency_code" => "HKD", "dependency_status" => "Part of CN"),
            array("cca2" => "BG", "cca3" => "BGR", "name" => "Bulgaria", "tld" => ".bg", "calling_code" => "359", "currency_code" => "BGN", "dependency_status" => null),
            array("cca2" => "TG", "cca3" => "TGO", "name" => "Togo", "tld" => ".tg", "calling_code" => "228", "currency_code" => "XOF", "dependency_status" => null),
            array("cca2" => "RS", "cca3" => "SRB", "name" => "Serbia", "tld" => ".rs", "calling_code" => "381", "currency_code" => "RSD", "dependency_status" => null),
            array("cca2" => "SL", "cca3" => "SLE", "name" => "Sierra Leone", "tld" => ".sl", "calling_code" => "232", "currency_code" => "SLL", "dependency_status" => null),
            array("cca2" => "PY", "cca3" => "PRY", "name" => "Paraguay", "tld" => ".py", "calling_code" => "595", "currency_code" => "PYG", "dependency_status" => null),
            array("cca2" => "SV", "cca3" => "SLV", "name" => "El Salvador", "tld" => ".sv", "calling_code" => "503", "currency_code" => "SVC,USD", "dependency_status" => null),
            array("cca2" => "LA", "cca3" => "LAO", "name" => "Laos", "tld" => ".la", "calling_code" => "856", "currency_code" => "LAK", "dependency_status" => null),
            array("cca2" => "LY", "cca3" => "LBY", "name" => "Libya", "tld" => ".ly", "calling_code" => "218", "currency_code" => "LYD", "dependency_status" => null),
            array("cca2" => "IE", "cca3" => "IRL", "name" => "Ireland", "tld" => ".ie", "calling_code" => "353", "currency_code" => "EUR", "dependency_status" => null),
            array("cca2" => "NI", "cca3" => "NIC", "name" => "Nicaragua", "tld" => ".ni", "calling_code" => "505", "currency_code" => "NIO", "dependency_status" => null),
            array("cca2" => "KG", "cca3" => "KGZ", "name" => "Kyrgyzstan", "tld" => ".kg", "calling_code" => "996", "currency_code" => "KGS", "dependency_status" => null),
            array("cca2" => "LB", "cca3" => "LBN", "name" => "Lebanon", "tld" => ".lb", "calling_code" => "961", "currency_code" => "LBP", "dependency_status" => null),
            array("cca2" => "DK", "cca3" => "DNK", "name" => "Denmark", "tld" => ".dk", "calling_code" => "45", "currency_code" => "DKK", "dependency_status" => null),
            array("cca2" => "SG", "cca3" => "SGP", "name" => "Singapore", "tld" => ".sg", "calling_code" => "65", "currency_code" => "SGD", "dependency_status" => null),
            array("cca2" => "FI", "cca3" => "FIN", "name" => "Finland", "tld" => ".fi", "calling_code" => "358", "currency_code" => "EUR", "dependency_status" => null),
            array("cca2" => "SK", "cca3" => "SVK", "name" => "Slovakia", "tld" => ".sk", "calling_code" => "421", "currency_code" => "EUR", "dependency_status" => null),
            array("cca2" => "ER", "cca3" => "ERI", "name" => "Eritrea", "tld" => ".er", "calling_code" => "291", "currency_code" => "ERN", "dependency_status" => null),
            array("cca2" => "NO", "cca3" => "NOR", "name" => "Norway", "tld" => ".no", "calling_code" => "47", "currency_code" => "NOK", "dependency_status" => null),
            array("cca2" => "CF", "cca3" => "CAF", "name" => "Central African Republic", "tld" => ".cf", "calling_code" => "236", "currency_code" => "XAF", "dependency_status" => null),
            array("cca2" => "CR", "cca3" => "CRI", "name" => "Costa Rica", "tld" => ".cr", "calling_code" => "506", "currency_code" => "CRC", "dependency_status" => null),
            array("cca2" => "TM", "cca3" => "TKM", "name" => "Turkmenistan", "tld" => ".tm", "calling_code" => "993", "currency_code" => "TMT", "dependency_status" => null),
            array("cca2" => "CG", "cca3" => "COG", "name" => "Congo - Brazzaville", "tld" => ".cg", "calling_code" => "242", "currency_code" => "XAF", "dependency_status" => null),
            array("cca2" => "NZ", "cca3" => "NZL", "name" => "New Zealand", "tld" => ".nz", "calling_code" => "64", "currency_code" => "NZD", "dependency_status" => null),
            array("cca2" => "PS", "cca3" => "PSE", "name" => "Palestine", "tld" => ".ps", "calling_code" => "970", "currency_code" => "---", "dependency_status" => "In contention"),
            array("cca2" => "LR", "cca3" => "LBR", "name" => "Liberia", "tld" => ".lr", "calling_code" => "231", "currency_code" => "LRD", "dependency_status" => null),
            array("cca2" => "OM", "cca3" => "OMN", "name" => "Oman", "tld" => ".om", "calling_code" => "968", "currency_code" => "OMR", "dependency_status" => null),
            array("cca2" => "HR", "cca3" => "HRV", "name" => "Croatia", "tld" => ".hr", "calling_code" => "385", "currency_code" => "HRK", "dependency_status" => null),
            array("cca2" => "KW", "cca3" => "KWT", "name" => "Kuwait", "tld" => ".kw", "calling_code" => "965", "currency_code" => "KWD", "dependency_status" => null),
            array("cca2" => "PA", "cca3" => "PAN", "name" => "Panama", "tld" => ".pa", "calling_code" => "507", "currency_code" => "PAB,USD", "dependency_status" => null),
            array("cca2" => "GE", "cca3" => "GEO", "name" => "Georgia", "tld" => ".ge", "calling_code" => "995", "currency_code" => "GEL", "dependency_status" => null),
            array("cca2" => "MR", "cca3" => "MRT", "name" => "Mauritania", "tld" => ".mr", "calling_code" => "222", "currency_code" => "MRU", "dependency_status" => null),
            array("cca2" => "MD", "cca3" => "MDA", "name" => "Moldova", "tld" => ".md", "calling_code" => "373", "currency_code" => "MDL", "dependency_status" => null),
            array("cca2" => "BA", "cca3" => "BIH", "name" => "Bosnia", "tld" => ".ba", "calling_code" => "387", "currency_code" => "BAM", "dependency_status" => null),
            array("cca2" => "UY", "cca3" => "URY", "name" => "Uruguay", "tld" => ".uy", "calling_code" => "598", "currency_code" => "UYU", "dependency_status" => null),
            array("cca2" => "PR", "cca3" => "PRI", "name" => "Puerto Rico", "tld" => ".pr", "calling_code" => "1", "currency_code" => "USD", "dependency_status" => "Commonwealth of US"),
            array("cca2" => "GB-WLS", "cca3" => "GB-WLS", "name" => "Wales", "tld" => ".wales", "calling_code" => "44", "currency_code" => "GBP", "dependency_status" => "Part of the UK"),
            array("cca2" => "MN", "cca3" => "MNG", "name" => "Mongolia", "tld" => ".mn", "calling_code" => "976", "currency_code" => "MNT", "dependency_status" => null),
            array("cca2" => "AL", "cca3" => "ALB", "name" => "Albania", "tld" => ".al", "calling_code" => "355", "currency_code" => "ALL", "dependency_status" => null),
            array("cca2" => "AM", "cca3" => "ARM", "name" => "Armenia", "tld" => ".am", "calling_code" => "374", "currency_code" => "AMD", "dependency_status" => null),
            array("cca2" => "LT", "cca3" => "LTU", "name" => "Lithuania", "tld" => ".lt", "calling_code" => "370", "currency_code" => "EUR", "dependency_status" => null),
            array("cca2" => "JM", "cca3" => "JAM", "name" => "Jamaica", "tld" => ".jm", "calling_code" => "1-876", "currency_code" => "JMD", "dependency_status" => null),
            array("cca2" => "QA", "cca3" => "QAT", "name" => "Qatar", "tld" => ".qa", "calling_code" => "974", "currency_code" => "QAR", "dependency_status" => null),
            array("cca2" => "NA", "cca3" => "NAM", "name" => "Namibia", "tld" => ".na", "calling_code" => "264", "currency_code" => "NAD,ZAR", "dependency_status" => null),
            array("cca2" => "BW", "cca3" => "BWA", "name" => "Botswana", "tld" => ".bw", "calling_code" => "267", "currency_code" => "BWP", "dependency_status" => null),
            array("cca2" => "SI", "cca3" => "SVN", "name" => "Slovenia", "tld" => ".si", "calling_code" => "386", "currency_code" => "EUR", "dependency_status" => null),
            array("cca2" => "MK", "cca3" => "MKD", "name" => "North Macedonia", "tld" => ".mk", "calling_code" => "389", "currency_code" => "MKD", "dependency_status" => null),
            array("cca2" => "LV", "cca3" => "LVA", "name" => "Latvia", "tld" => ".lv", "calling_code" => "371", "currency_code" => "EUR", "dependency_status" => null),
            array("cca2" => "LS", "cca3" => "LSO", "name" => "Lesotho", "tld" => ".ls", "calling_code" => "266", "currency_code" => "LSL,ZAR", "dependency_status" => null),
            array("cca2" => "GM", "cca3" => "GMB", "name" => "Gambia", "tld" => ".gm", "calling_code" => "220", "currency_code" => "GMD", "dependency_status" => null),
            array("cca2" => "GA", "cca3" => "GAB", "name" => "Gabon", "tld" => ".ga", "calling_code" => "241", "currency_code" => "XAF", "dependency_status" => null),
            array("cca2" => "XK", "cca3" => "XKX", "name" => "Kosovo", "tld" => ".xk", "calling_code" => "383", "currency_code" => "EUR", "dependency_status" => "In contention"),
            array("cca2" => "GW", "cca3" => "GNB", "name" => "Guinea-Bissau", "tld" => ".gw", "calling_code" => "245", "currency_code" => "XOF", "dependency_status" => null),
            array("cca2" => "BH", "cca3" => "BHR", "name" => "Bahrain", "tld" => ".bh", "calling_code" => "973", "currency_code" => "BHD", "dependency_status" => null),
            array("cca2" => "TT", "cca3" => "TTO", "name" => "Trinidad & Tobago", "tld" => ".tt", "calling_code" => "1-868", "currency_code" => "TTD", "dependency_status" => null),
            array("cca2" => "EE", "cca3" => "EST", "name" => "Estonia", "tld" => ".ee", "calling_code" => "372", "currency_code" => "EUR", "dependency_status" => null),
            array("cca2" => "MU", "cca3" => "MUS", "name" => "Mauritius", "tld" => ".mu", "calling_code" => "230", "currency_code" => "MUR", "dependency_status" => null),
            array("cca2" => "GQ", "cca3" => "GNQ", "name" => "Equatorial Guinea", "tld" => ".gq", "calling_code" => "240", "currency_code" => "XAF", "dependency_status" => null),
            array("cca2" => "TL", "cca3" => "TLS", "name" => "Timor-Leste", "tld" => ".tl", "calling_code" => "670", "currency_code" => "USD", "dependency_status" => null),
            array("cca2" => "SZ", "cca3" => "SWZ", "name" => "Eswatini", "tld" => ".sz", "calling_code" => "268", "currency_code" => "SZL", "dependency_status" => null),
            array("cca2" => "DJ", "cca3" => "DJI", "name" => "Djibouti", "tld" => ".dj", "calling_code" => "253", "currency_code" => "DJF", "dependency_status" => null),
            array("cca2" => "FJ", "cca3" => "FJI", "name" => "Fiji", "tld" => ".fj", "calling_code" => "679", "currency_code" => "FJD", "dependency_status" => null),
            array("cca2" => "CY", "cca3" => "CYP", "name" => "Cyprus", "tld" => ".cy", "calling_code" => "357", "currency_code" => "EUR", "dependency_status" => null),
            array("cca2" => "RE", "cca3" => "REU", "name" => "Réunion", "tld" => ".re", "calling_code" => "262", "currency_code" => "EUR", "dependency_status" => "Part of FR"),
            array("cca2" => "KM", "cca3" => "COM", "name" => "Comoros", "tld" => ".km", "calling_code" => "269", "currency_code" => "KMF", "dependency_status" => null),
            array("cca2" => "BT", "cca3" => "BTN", "name" => "Bhutan", "tld" => ".bt", "calling_code" => "975", "currency_code" => "INR,BTN", "dependency_status" => null),
            array("cca2" => "GY", "cca3" => "GUY", "name" => "Guyana", "tld" => ".gy", "calling_code" => "592", "currency_code" => "GYD", "dependency_status" => null),
            array("cca2" => "MO", "cca3" => "MAC", "name" => "Macau", "tld" => ".mo", "calling_code" => "853", "currency_code" => "MOP", "dependency_status" => "Part of CN"),
            array("cca2" => "SB", "cca3" => "SLB", "name" => "Solomon Islands", "tld" => ".sb", "calling_code" => "677", "currency_code" => "SBD", "dependency_status" => null),
            array("cca2" => "ME", "cca3" => "MNE", "name" => "Montenegro", "tld" => ".me", "calling_code" => "382", "currency_code" => "EUR", "dependency_status" => null),
            array("cca2" => "LU", "cca3" => "LUX", "name" => "Luxembourg", "tld" => ".lu", "calling_code" => "352", "currency_code" => "EUR", "dependency_status" => null),
            array("cca2" => "SR", "cca3" => "SUR", "name" => "Suriname", "tld" => ".sr", "calling_code" => "597", "currency_code" => "SRD", "dependency_status" => null),
            array("cca2" => "CV", "cca3" => "CPV", "name" => "Cape Verde", "tld" => ".cv", "calling_code" => "238", "currency_code" => "CVE", "dependency_status" => null),
            array("cca2" => "EH", "cca3" => "ESH", "name" => "Western Sahara", "tld" => ".eh", "calling_code" => "212", "currency_code" => "MAD", "dependency_status" => "In contention"),
            array("cca2" => "MT", "cca3" => "MLT", "name" => "Malta", "tld" => ".mt", "calling_code" => "356", "currency_code" => "EUR", "dependency_status" => null),
            array("cca2" => "BN", "cca3" => "BRN", "name" => "Brunei", "tld" => ".bn", "calling_code" => "673", "currency_code" => "BND", "dependency_status" => null),
            array("cca2" => "GP", "cca3" => "GLP", "name" => "Guadeloupe", "tld" => ".gp", "calling_code" => "590", "currency_code" => "EUR", "dependency_status" => "Part of FR"),
            array("cca2" => "MQ", "cca3" => "MTQ", "name" => "Martinique", "tld" => ".mq", "calling_code" => "596", "currency_code" => "EUR", "dependency_status" => "Part of FR"),
            array("cca2" => "BS", "cca3" => "BHS", "name" => "Bahamas", "tld" => ".bs", "calling_code" => "1-242", "currency_code" => "BSD", "dependency_status" => null),
            array("cca2" => "BZ", "cca3" => "BLZ", "name" => "Belize", "tld" => ".bz", "calling_code" => "501", "currency_code" => "BZD", "dependency_status" => null),
            array("cca2" => "MV", "cca3" => "MDV", "name" => "Maldives", "tld" => ".mv", "calling_code" => "960", "currency_code" => "MVR", "dependency_status" => null),
            array("cca2" => "IS", "cca3" => "ISL", "name" => "Iceland", "tld" => ".is", "calling_code" => "354", "currency_code" => "ISK", "dependency_status" => null),
            array("cca2" => "BB", "cca3" => "BRB", "name" => "Barbados", "tld" => ".bb", "calling_code" => "1-246", "currency_code" => "BBD", "dependency_status" => null),
            array("cca2" => "VU", "cca3" => "VUT", "name" => "Vanuatu", "tld" => ".vu", "calling_code" => "678", "currency_code" => "VUV", "dependency_status" => null),
            array("cca2" => "PF", "cca3" => "PYF", "name" => "French Polynesia", "tld" => ".pf", "calling_code" => "689", "currency_code" => "XPF", "dependency_status" => "Territory of FR"),
            array("cca2" => "NC", "cca3" => "NCL", "name" => "New Caledonia", "tld" => ".nc", "calling_code" => "687", "currency_code" => "XPF", "dependency_status" => "Territory of FR"),
            array("cca2" => "GF", "cca3" => "GUF", "name" => "French Guiana", "tld" => ".gf", "calling_code" => "594", "currency_code" => "EUR", "dependency_status" => "Part of FR"),
            array("cca2" => "YT", "cca3" => "MYT", "name" => "Mayotte", "tld" => ".yt", "calling_code" => "262", "currency_code" => "EUR", "dependency_status" => "Part of FR"),
            array("cca2" => "ST", "cca3" => "STP", "name" => "São Tomé & Príncipe", "tld" => ".st", "calling_code" => "239", "currency_code" => "STN", "dependency_status" => null),
            array("cca2" => "LC", "cca3" => "LCA", "name" => "St. Lucia", "tld" => ".lc", "calling_code" => "1-758", "currency_code" => "XCD", "dependency_status" => null),
            array("cca2" => "GU", "cca3" => "GUM", "name" => "Guam", "tld" => ".gu", "calling_code" => "1-671", "currency_code" => "USD", "dependency_status" => "Territory of US"),
            array("cca2" => "CW", "cca3" => "CUW", "name" => "Curaçao", "tld" => ".cw", "calling_code" => "599", "currency_code" => "ANG", "dependency_status" => "Part of NL"),
            array("cca2" => "VI", "cca3" => "VIR", "name" => "U.S. Virgin Islands", "tld" => ".vi", "calling_code" => "1-340", "currency_code" => "USD", "dependency_status" => "Territory of US"),
            array("cca2" => "KI", "cca3" => "KIR", "name" => "Kiribati", "tld" => ".ki", "calling_code" => "686", "currency_code" => "AUD", "dependency_status" => null),
            array("cca2" => "VC", "cca3" => "VCT", "name" => "St. Vincent & Grenadines", "tld" => ".vc", "calling_code" => "1-784", "currency_code" => "XCD", "dependency_status" => null),
            array("cca2" => "AW", "cca3" => "ABW", "name" => "Aruba", "tld" => ".aw", "calling_code" => "297", "currency_code" => "AWG", "dependency_status" => "Part of NL"),
            array("cca2" => "GD", "cca3" => "GRD", "name" => "Grenada", "tld" => ".gd", "calling_code" => "1-473", "currency_code" => "XCD", "dependency_status" => null),
            array("cca2" => "TO", "cca3" => "TON", "name" => "Tonga", "tld" => ".to", "calling_code" => "676", "currency_code" => "TOP", "dependency_status" => null),
            array("cca2" => "FM", "cca3" => "FSM", "name" => "Micronesia", "tld" => ".fm", "calling_code" => "691", "currency_code" => "USD", "dependency_status" => null),
            array("cca2" => "JE", "cca3" => "JEY", "name" => "Jersey", "tld" => ".je", "calling_code" => "44", "currency_code" => "GBP", "dependency_status" => "Crown dependency of GB"),
            array("cca2" => "SC", "cca3" => "SYC", "name" => "Seychelles", "tld" => ".sc", "calling_code" => "248", "currency_code" => "SCR", "dependency_status" => null),
            array("cca2" => "AG", "cca3" => "ATG", "name" => "Antigua & Barbuda", "tld" => ".ag", "calling_code" => "1-268", "currency_code" => "XCD", "dependency_status" => null),
            array("cca2" => "IM", "cca3" => "IMN", "name" => "Isle of Man", "tld" => ".im", "calling_code" => "44", "currency_code" => "GBP", "dependency_status" => "Crown dependency of GB"),
            array("cca2" => "AD", "cca3" => "AND", "name" => "Andorra", "tld" => ".ad", "calling_code" => "376", "currency_code" => "EUR", "dependency_status" => null),
            array("cca2" => "DM", "cca3" => "DMA", "name" => "Dominica", "tld" => ".dm", "calling_code" => "1-767", "currency_code" => "XCD", "dependency_status" => null),
            array("cca2" => "GG", "cca3" => "GGY", "name" => "Guernsey", "tld" => ".gg", "calling_code" => "44", "currency_code" => "GBP", "dependency_status" => "Crown dependency of GB"),
            array("cca2" => "BM", "cca3" => "BMU", "name" => "Bermuda", "tld" => ".bm", "calling_code" => "1-441", "currency_code" => "BMD", "dependency_status" => "Territory of GB"),
            array("cca2" => "KY", "cca3" => "CYM", "name" => "Cayman Islands", "tld" => ".ky", "calling_code" => "1-345", "currency_code" => "KYD", "dependency_status" => "Territory of GB"),
            array("cca2" => "AS", "cca3" => "ASM", "name" => "American Samoa", "tld" => ".as", "calling_code" => "1-684", "currency_code" => "USD", "dependency_status" => "Territory of US"),
            array("cca2" => "MP", "cca3" => "MNP", "name" => "Northern Mariana Islands", "tld" => ".mp", "calling_code" => "1-670", "currency_code" => "USD", "dependency_status" => "Commonwealth of US"),
            array("cca2" => "GL", "cca3" => "GRL", "name" => "Greenland", "tld" => ".gl", "calling_code" => "299", "currency_code" => "DKK", "dependency_status" => "Part of DK"),
            array("cca2" => "MH", "cca3" => "MHL", "name" => "Marshall Islands", "tld" => ".mh", "calling_code" => "692", "currency_code" => "USD", "dependency_status" => null),
            array("cca2" => "FO", "cca3" => "FRO", "name" => "Faroe Islands", "tld" => ".fo", "calling_code" => "298", "currency_code" => "DKK", "dependency_status" => "Part of DK"),
            array("cca2" => "KN", "cca3" => "KNA", "name" => "St. Kitts & Nevis", "tld" => ".kn", "calling_code" => "1-869", "currency_code" => "XCD", "dependency_status" => null),
            array("cca2" => "MC", "cca3" => "MCO", "name" => "Monaco", "tld" => ".mc", "calling_code" => "377", "currency_code" => "EUR", "dependency_status" => null),
            array("cca2" => "SX", "cca3" => "SXM", "name" => "Sint Maarten", "tld" => ".sx", "calling_code" => "1-721", "currency_code" => "ANG", "dependency_status" => "Part of NL"),
            array("cca2" => "LI", "cca3" => "LIE", "name" => "Liechtenstein", "tld" => ".li", "calling_code" => "423", "currency_code" => "CHF", "dependency_status" => null),
            array("cca2" => "MF", "cca3" => "MAF", "name" => "St. Martin", "tld" => ".gp", "calling_code" => "590", "currency_code" => "EUR", "dependency_status" => "Part of FR"),
            array("cca2" => "GI", "cca3" => "GIB", "name" => "Gibraltar", "tld" => ".gi", "calling_code" => "350", "currency_code" => "GIP", "dependency_status" => "Territory of GB"),
            array("cca2" => "SM", "cca3" => "SMR", "name" => "San Marino", "tld" => ".sm", "calling_code" => "378", "currency_code" => "EUR", "dependency_status" => null),
            array("cca2" => "TC", "cca3" => "TCA", "name" => "Turks & Caicos Islands", "tld" => ".tc", "calling_code" => "1-649", "currency_code" => "USD", "dependency_status" => "Territory of GB"),
            array("cca2" => "AX", "cca3" => "ALA", "name" => "Åland Islands", "tld" => ".ax", "calling_code" => "358", "currency_code" => "EUR", "dependency_status" => "Part of FI"),
            array("cca2" => "VG", "cca3" => "VGB", "name" => "British Virgin Islands", "tld" => ".vg", "calling_code" => "1-284", "currency_code" => "USD", "dependency_status" => "Territory of GB"),
            array("cca2" => "CK", "cca3" => "COK", "name" => "Cook Islands", "tld" => ".ck", "calling_code" => "682", "currency_code" => "NZD", "dependency_status" => "Associated with NZ"),
            array("cca2" => "PW", "cca3" => "PLW", "name" => "Palau", "tld" => ".pw", "calling_code" => "680", "currency_code" => "USD", "dependency_status" => null),
            array("cca2" => "BQ", "cca3" => "BES", "name" => "Caribbean Netherlands", "tld" => ".bq", "calling_code" => "599", "currency_code" => "USD", "dependency_status" => "Part of NL"),
            array("cca2" => "AI", "cca3" => "AIA", "name" => "Anguilla", "tld" => ".ai", "calling_code" => "1-264", "currency_code" => "XCD", "dependency_status" => "Territory of GB"),
            array("cca2" => "WF", "cca3" => "WLF", "name" => "Wallis & Futuna", "tld" => ".wf", "calling_code" => "681", "currency_code" => "XPF", "dependency_status" => "Territory of FR"),
            array("cca2" => "TV", "cca3" => "TUV", "name" => "Tuvalu", "tld" => ".tv", "calling_code" => "688", "currency_code" => "AUD", "dependency_status" => null),
            array("cca2" => "NR", "cca3" => "NRU", "name" => "Nauru", "tld" => ".nr", "calling_code" => "674", "currency_code" => "AUD", "dependency_status" => null),
            array("cca2" => "BL", "cca3" => "BLM", "name" => "St. Barthélemy", "tld" => ".gp", "calling_code" => "590", "currency_code" => "EUR", "dependency_status" => "Part of FR"),
            array("cca2" => "PM", "cca3" => "SPM", "name" => "St. Pierre & Miquelon", "tld" => ".pm", "calling_code" => "508", "currency_code" => "EUR", "dependency_status" => "Part of FR"),
            array("cca2" => "MS", "cca3" => "MSR", "name" => "Montserrat", "tld" => ".ms", "calling_code" => "1-664", "currency_code" => "XCD", "dependency_status" => "Territory of GB"),
            array("cca2" => "SH", "cca3" => "SHN", "name" => "St. Helena", "tld" => ".sh", "calling_code" => "290", "currency_code" => "SHP", "dependency_status" => "Territory of GB"),
            array("cca2" => "IO", "cca3" => "IOT", "name" => "British Indian Ocean Territory", "tld" => ".io", "calling_code" => "246", "currency_code" => "USD", "dependency_status" => "Territory of GB"),
            array("cca2" => "FK", "cca3" => "FLK", "name" => "Falkland Islands", "tld" => ".fk", "calling_code" => "500", "currency_code" => "FKP", "dependency_status" => "Territory of GB"),
            array("cca2" => "SJ", "cca3" => "SJM", "name" => "Svalbard & Jan Mayen", "tld" => ".sj", "calling_code" => "47", "currency_code" => "NOK", "dependency_status" => "Territory of NO"),
            array("cca2" => "NF", "cca3" => "NFK", "name" => "Norfolk Island", "tld" => ".nf", "calling_code" => "672", "currency_code" => "AUD", "dependency_status" => "Territory of AU"),
            array("cca2" => "CX", "cca3" => "CXR", "name" => "Christmas Island", "tld" => ".cx", "calling_code" => "61", "currency_code" => "AUD", "dependency_status" => "Territory of AU"),
            array("cca2" => "NU", "cca3" => "NIU", "name" => "Niue", "tld" => ".nu", "calling_code" => "683", "currency_code" => "NZD", "dependency_status" => "Associated with NZ"),
            array("cca2" => "TK", "cca3" => "TKL", "name" => "Tokelau", "tld" => ".tk", "calling_code" => "690", "currency_code" => "NZD", "dependency_status" => "Territory of NZ"),
            array("cca2" => "AQ", "cca3" => "ATA", "name" => "Antarctica", "tld" => ".aq", "calling_code" => "672", "currency_code" => "---", "dependency_status" => "International"),
            array("cca2" => "CC", "cca3" => "CCK", "name" => "Cocos (Keeling) Islands", "tld" => ".cc", "calling_code" => "61", "currency_code" => "AUD", "dependency_status" => "Territory of AU"),
            array("cca2" => "VA", "cca3" => "VAT", "name" => "Vatican City", "tld" => ".va", "calling_code" => "39-06", "currency_code" => "EUR", "dependency_status" => null),
            array("cca2" => "UM", "cca3" => "UMI", "name" => "U.S. Outlying Islands", "tld" => ".us", "calling_code" => "1", "currency_code" => "USD", "dependency_status" => "Territories of US"),
            array("cca2" => "TF", "cca3" => "ATF", "name" => "French Southern Territories", "tld" => ".tf", "calling_code" => "262", "currency_code" => "EUR", "dependency_status" => "Territory of FR"),
            array("cca2" => "PN", "cca3" => "PCN", "name" => "Pitcairn Islands", "tld" => ".pn", "calling_code" => "870", "currency_code" => "NZD", "dependency_status" => "Territory of GB"),
            array("cca2" => "GS", "cca3" => "SGS", "name" => "South Georgia & South Sandwich Islands", "tld" => ".gs", "calling_code" => "500", "currency_code" => "FKP", "dependency_status" => "Territory of GB"),
            array("cca2" => "HM", "cca3" => "HMD", "name" => "Heard & McDonald Islands", "tld" => ".hm", "calling_code" => "672", "currency_code" => "AUD", "dependency_status" => "Territory of AU"),
            array("cca2" => "BV", "cca3" => "BVT", "name" => "Bouvet Island", "tld" => ".bv", "calling_code" => "47", "currency_code" => "NOK", "dependency_status" => "Territory of NO"),
        );
        DB::table('bear_country')->insert($country);
    }

    public function down(): void {
        Schema::dropIfExists('bear_country');
    }
};
